model_name: XGBoost (Tuned)
model_type: xgboost_tuned
params:
  n_estimators: 2000
  max_depth: 8
  learning_rate: 0.03
  subsample: 0.7
  colsample_bytree: 0.7
  reg_alpha: 0.1
  reg_lambda: 2.0
  min_child_weight: 10
  tree_method: hist
  n_jobs: -1
  random_state: 42
  verbosity: 0
  early_stopping_rounds: 100
scaling: false
